# =========================================
# Rank Progression Configuration Paper v1.0
# =========================================

# The name for the paper server
server-name: server

# How often to update playtime and check for promotions (in minutes)
check-interval: 1

# Allow promotions in server?
# If set to false, playtime is still tracked but players must connect to another server to get promoted
allow-promotions: true

# Broadcast promotions to the whole server?
# If set to false, promotion messages will only send to the player directly
broadcast-promotions: true