name: Rank-Progression
version: '0.4.0'
main: me.RedEagle3.rankProgression.RankProgression
api-version: '1.21'

description: A custom rank progression and playtime tracking system for the ERRSA Minecraft server.
author: The ERRSA MC Dev Team
website: https://campusgroups.erau.edu/errsa/craft/

commands:
  playtime:
    description: Displays your playtime statistics.
    aliases: [pt]
    permission: rankprogression.playtime
  progression:
    description: Opens the rank progression GUI.
    permission: rankprogression.progression
  syncrankprogression:
    description: Syncs all offline player's data into the proxy YML.
    permission: rankprogression.syncrankprogression
  exportplaytimedata:
    description: Exports playtime data as an excel sheet for analytics.
    permission: rankprogression.exportplaytimedata

permissions:
  rankprogression.autopromote:
    description: Allows the player to be promoted when hitting playtime milestones.