# ============================================
# Rank Progression Configuration Velocity v1.0
# ============================================

# LuckPerms track name
track-name: "rank_progression"

# Rank milestones
ranks:
  coal:
    requirement: 1h
    rewards:
      - "Coming soon..."
    icon: "●"
    color: "&0"
  iron:
    requirement: 3h
    rewards:
      - "Coming soon..."
    icon: "▲"
    color: "&8"
  quartz:
    requirement: 5h
    rewards:
      - "Coming soon..."
    icon: "■"
    color: "&f"
  copper:
    requirement: 12h
    rewards:
      - "Coming soon..."
    icon: "⬟"
    color: "&6"
  gold:
    requirement: 24h
    rewards:
      - "Coming soon..."
    icon: "⬣"
    color: "&e"
  lapis:
    requirement: 48h
    rewards:
      - "Coming soon..."
    icon: "✿"
    color: "&9"
  redstone:
    requirement: 96h
    rewards:
      - "Coming soon..."
    icon: "⚡"
    color: "&c"
  amethyst:
    requirement: 150h
    rewards:
      - "Coming soon..."
    icon: "◆"
    color: "&d"
  emerald:
    requirement: 250h
    rewards:
      - "Coming soon..."
    icon: "♣"
    color: "&a"
  diamond:
    requirement: 400h
    rewards:
      - "Coming soon..."
    icon: "♦"
    color: "&b"
  netherite:
    requirement: 650h
    rewards:
      - "Coming soon..."
    icon: "⌘"
    color: "&4"
  echo:
    requirement: 1000h
    rewards:
      - "Coming soon..."
    icon: "∞"
    color: "&1"
  ender:
    requirement: 1500h
    rewards:
      - "Coming soon..."
    icon: "❇"
    color: "&5"
  astral:
    requirement: 2500h
    rewards:
      - "Coming soon..."
    icon: "✳"
    color: "&3"
  zenith:
    requirement: 10000h
    rewards:
      - "Coming soon..."
    icon: "☠"
    color: "&4"